name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar o java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Executar test
        run: mvn clean package

      - name: Guardar o jar
        uses: actions/upload-artifact@v4
        with:
          name: testededeploy-jar
          path: target/testededeploy-0.0.1-SNAPSHOT.jar

  verify-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar jar
        uses: actions/download-artifact@v4
        with:
          name: testededeploy-jar

      - name: Executar app
        run: |
          java -jar testededeploy-0.0.1-SNAPSHOT.jar &
          sleep 10
          curl "http://localhost:8080/teste"